odometry_node:
  ros__parameters:
    p0:
      x: 0.0
      y: 0.0
    p1:
      x: 8.0
      y: 0.0
    p2:
      x: 0.0
      y: 7.0
    p3:
      x: 0.0
      y: -7.0
    p4:
      x: -8.0
      y: 0.0